name: Build and Test
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        
    steps:
    - name: Build Application
      run: npm run compile
    - name: Run tests
      run: npm test
